version: '3'
services:
  postgres_db25:
    image: postgres:14-alpine
    container_name: "postgres${PORT}"
    environment:
      - "POSTGRES_PASSWORD=${PSQL_PASS}"
      - "POSTGRES_DB=${PSQL_DB}"
      - "POSTGRES_USER=$PSQL_USER"
    ports:
      - "100${PORT}:55${PORT}"
    volumes:
      - "${DJANGO_VOLUME_PATH}:/usr/src/postgres"
    # - "/home/luis_gonzalez/postgres:/usr/src/postgres"

    networks:
      - our-library-net
    command: " -p 55${PORT}"

  web25:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pytest && python manage.py runserver 0.0.0.0:80${PORT}"
    container_name: "django${PORT}"
    depends_on: 
      - postgres_db25
    environment:
      - "PSQL_DBNAME=${PSQL_DB}"
      - "PSQL_USERNAME=${PSQL_USER}"
      - "PSQL_PASS=${PSQL_PASS}"
      - "PSQL_HOST=postgres_db${PORT}" 
      - "JWT_TOKEN_TIME=${JWT_TOKEN_TIME}"
      - "PSQL_PORT=55${PORT}"
    volumes:
    # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "${DJANGO_VOLUME_PATH}:/usr/src/django/library"
      # -"/home/luis_gonzalez/django/restpy/Django-REST-Exercise:/usr/src/django/library"
      

    ports:
      - "90${PORT}:80${PORT}"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge