name: Workflow without docker

on:
    workflow_call:
    workflow_dispatch:
    push:
      branches: [main]
    pull_request:
      branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup django
      uses: actions/checkout@v2
    - name: Setup python 3.10.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4
    - run: |
        pip install -r requirements.txt
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'

    #   postgres_main:
    #     image: postgres:latest
    #     env:
    #         PSQL_USER: luis_gonzalez
    #         PSQL_PASS: luis_pass
    #         PSQL_DB: luis_gonzalezdb
    #       ports:
    #        - 5432:5432
    #       options: >-
    #         --health-cmd pg_isready 
    #         --health-interval 10s 
    #         --health-timeout 5s 
    #         --health-retries 5
    #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # steps:
    #   - name: Run Tests
    #     run: |
    #        python manage.py tests
      